# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cart.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\x04\x63\x61rt\"8\n\x04\x43\x61rt\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\",\n\x0eGetCartRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x03(\t\"E\n\x11\x43reateCartRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"(\n\x0c\x43\x61rtResponse\x12\x18\n\x04\x63\x61rt\x18\x01 \x01(\x0b\x32\n.cart.Cart\"%\n\x12\x43reateCartResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x83\x01\n\x0b\x43\x61rtService\x12\x33\n\x07GetCart\x12\x14.cart.GetCartRequest\x1a\x12.cart.CartResponse\x12?\n\nCreateCart\x12\x17.cart.CreateCartRequest\x1a\x18.cart.CreateCartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CART']._serialized_start=20
  _globals['_CART']._serialized_end=76
  _globals['_GETCARTREQUEST']._serialized_start=78
  _globals['_GETCARTREQUEST']._serialized_end=122
  _globals['_CREATECARTREQUEST']._serialized_start=124
  _globals['_CREATECARTREQUEST']._serialized_end=193
  _globals['_CARTRESPONSE']._serialized_start=195
  _globals['_CARTRESPONSE']._serialized_end=235
  _globals['_CREATECARTRESPONSE']._serialized_start=237
  _globals['_CREATECARTRESPONSE']._serialized_end=274
  _globals['_CARTSERVICE']._serialized_start=277
  _globals['_CARTSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
