# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"=\n\x0cOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"1\n\rOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\rRefundRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x82\x01\n\x0cOrderService\x12\x37\n\nPlaceOrder\x12\x13.order.OrderRequest\x1a\x14.order.OrderResponse\x12\x39\n\x0bRefundOrder\x12\x14.order.RefundRequest\x1a\x14.order.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=22
  _globals['_ORDERREQUEST']._serialized_end=83
  _globals['_ORDERRESPONSE']._serialized_start=85
  _globals['_ORDERRESPONSE']._serialized_end=134
  _globals['_REFUNDREQUEST']._serialized_start=136
  _globals['_REFUNDREQUEST']._serialized_end=163
  _globals['_ORDERSERVICE']._serialized_start=166
  _globals['_ORDERSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
